version: '3.7'
  
services:
    mariadb:
        image: mariadb:latest
        container_name: "mariadb"
        environment:
            - MYSQL_ROOT_PASSWORD=passwordroot
            - MYSQL_DATABASE=test_database
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=password
        networks:
            - mariadb-backend
        restart: always

    mariadb-backup:
        image: pofilo/mariadb-backup:latest
        container_name: "mariadb-backup"
        environment:
            - MARIADB_HOST=mariadb
            - MARIADB_USER=mysql
            - MARIADB_PASSWORD=password
        volumes:
            - ./backup/:/app/backup/
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - mariadb-backend
        depends_on: 
            - mariadb
        restart: always

networks:
    mariadb-backend:
        name: mariadb-backend

